server:
  port: 80

spring:
  application:
    name: cloud-payment-feign-consumer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

ribbon:
  #两端建立tcp连接所用的时间
  ReadTimeout: 5000
  #从服务端读取可用资源所需要的的时间
  ConnectTimeout: 5000

logging:
  level:
    com.atguigu.springcloud.services.PaymentFeignService: debug